### ISSUE TITLE
"calibre.utils.zipfile.BadZipfile: File is not a zip file" when execute convert method

### ISSUE THREAD

**Issue by danielnoliveira** [JVKdouk/node-ebook-converter#2]
when executing the conversion method, the error "caliber.utils.zipfile.BadZipfile: File is not a zip file" ends up occurring. The conversion was from an epub file to a mobi. The epub file is not corrupted. I ran the command ebook-converter from the terminal and the conversion worked. Any solution?

**Comment by JVKdouk** [comment]
Hey Daniel!
I will check that up today! Would you mind sending me a reproducible code and, if possible, the files you are using for conversion? If you cannot, then no problem!

**Comment by danielnoliveira** [comment]
> Hey Daniel!
> I will check that up today! Would you mind sending me a reproducible code and, if possible, the files you are using for conversion? If you cannot, then no problem!

It's here: https://github.com/danielnoliveira/TelegramBotKindle

**Comment by danielnoliveira** [comment]
Converting /home/daniel/Code Universe/NodeJS/TelegramBotKindle/books/Friedrich_Nietzsche_Crepúsculo_dos_Ídolos_Ou_como_se_filosofa_com.epub...
Error: Command failed: ebook-convert "/home/daniel/Code Universe/NodeJS/TelegramBotKindle/books/Friedrich_Nietzsche_Crepúsculo_dos_Ídolos_Ou_como_se_filosofa_com.epub" "/home/daniel/Code Universe/NodeJS/TelegramBotKindle/books/Friedrich_Nietzsche_Crepúsculo_dos_Ídolos_Ou_como_se_filosofa_com.mobi"
Traceback (most recent call last):
  File "calibre/ebooks/conversion/plugins/epub_input.py", line 262, in convert
  File "calibre/utils/zipfile.py", line 775, in __init__
  File "calibre/utils/zipfile.py", line 810, in _GetContents
  File "calibre/utils/zipfile.py", line 825, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/ebooks/conversion/cli.py", line 401, in main
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/epub_input.py", line 269, in convert
  File "calibre/utils/localunzip.py", line 253, in extractall
  File "calibre/utils/localunzip.py", line 235, in _extractall
  File "calibre/utils/localunzip.py", line 178, in copy_compressed_file
ValueError: Invalid ZIP file, local header is damaged

    at ChildProcess.exithandler (node:child_process:309:12)
    at ChildProcess.emit (node:events:329:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ebook-convert "/home/daniel/Code Universe/NodeJS/TelegramBotKindle/books/Friedrich_Nietzsche_Crepúsculo_dos_Ídolos_Ou_como_se_filosofa_com.epub" "/home/daniel/Code Universe/NodeJS/TelegramBotKindle/books/Friedrich_Nietzsche_Crepúsculo_dos_Ídolos_Ou_como_se_filosofa_com.mobi"'
}

**Comment by JVKdouk** [comment]
Just executed the code and it worked as it should. Can you please check the version of your calibre with: ```ebook-converter --version``` in your terminal?

**Comment by danielnoliveira** [comment]
> Just executed the code and it worked as it should. Can you please check the version of your calibre with: `ebook-converter --version` in your terminal?

5.9.0

**Comment by JVKdouk** [comment]
Same version. Weird, I will search for the problem in the official Calibre forums. Maybe the answer is there!

**Comment by JVKdouk** [comment]
Hey @danielnoliveira, after researching a little, I can see the EPUB you are trying to convert is technically invalid. EPUBs are basically ZIP files.

As I can see from your code, you are not trying to convert the EPUB from the books folder, but instead download it from Telegram, saving it, and then converting it. Maybe it would be a good idea to make a health check in the EPUB just to check if your script is actually waiting for it finish downloading before converting!

Please, try that and see if it works. I will be closing this issue for now as I don't believe this is a problem with the library itself. If the problem persists, feel free to reopen this issue!

**Comment by danielnoliveira** [comment]
> Hey @danielnoliveira, after researching a little, I can see the EPUB you are trying to convert is technically invalid. EPUBs are basically ZIP files.
> 
> As I can see from your code, you are not trying to convert the EPUB from the books folder, but instead download it from Telegram, saving it, and then converting it. Maybe it would be a good idea to make a health check in the EPUB just to check if your script is actually waiting for it finish downloading before converting!
> 
> Please, try that and see if it works. I will be closing this issue for now as I don't believe this is a problem with the library itself. If the problem persists, feel free to reopen this issue!

OK, thanks for the help
