### ISSUE TITLE
Error: option does not take a value

### ISSUE THREAD

**Issue by Alynva** [JVKdouk/node-ebook-converter#3]
Some of the parameters from here https://manual.calibre-ebook.com/generated/en/ebook-convert.html are just flags that doesn't receive a value. As an example, the `--mobi-ignore-margins`.

How to deal with this? I have try using `true`, but didn't work.

**Comment by Alynva** [comment]
Also, the `worker.on('error', error => reject(error));` doesn't catch this error, making my script never ends. I have try using `try { ... } catch { ... }` but didn't work.

**Comment by JVKdouk** [comment]
Hey @Alynva, just solved the problem!
Version 1.0.10 now brings a fix for boolean flags. Please, give it a try.
For now I will close this issue, but if the problem persists, feel free to reopen it!

**Comment by Alynva** [comment]
@JVKdouk look [this](https://github.com/JVKdouk/node-ebook-converter/commit/d072ecd626909a1344bbd4240ae94a209363f34d#r46013378)

**Comment by JVKdouk** [comment]
@Alynva problem solved. Sorry for that!
